#!/usr/bin/env python3
"""Deploy the DMCP Studio REPLAY demo to a Hugging Face Docker Space.

Uploads only the demo subset — the studio plus the ``dmcp`` and
``benchmark_advisor`` packages it imports — together with a root ``Dockerfile``
(the studio's own, which already builds from this layout) and the Space
``README.md``. It never uploads ``paper/``, ``docs/``, ``tests/``,
``node_modules/`` or ``frontend/dist`` (rebuilt by the image). HF then builds the
image (npm build -> editable install -> the ``e3_curate`` build-time smoke test)
and serves it on port 8000 in REPLAY mode (no API keys, no network).

The HF token is read from the git-ignored ``.env`` via python-dotenv — by default
``HF_TOKEN`` then ``HF_PERSONAL_TOKEN``, or a var named by ``--token-env``. It is
never printed. NB: hosting a Docker Space requires a paid HF plan (personal PRO
or an org Team/Enterprise plan); static Spaces are the only free option.

Prereqs:  pip install huggingface_hub python-dotenv   (both already deps here)
Usage:
  python dmcp-studio/deploy/hf-space/deploy.py --repo-id jrzkaminski/dmcp-studio --dry-run
  python dmcp-studio/deploy/hf-space/deploy.py --repo-id jrzkaminski/dmcp-studio \
      --token-env HF_PERSONAL_TOKEN --wait
"""

from __future__ import annotations

import argparse
import os
import shutil
import sys
import tempfile
import time
from pathlib import Path

HERE = Path(__file__).resolve()
ROOT = HERE.parents[3]  # repo root
SPACE_README = HERE.parent / "README.md"
DOCKERFILE = ROOT / "dmcp-studio" / "Dockerfile"
DOCKERIGNORE = ROOT / ".dockerignore"

# Directory names pruned while staging (regenerated by the image or irrelevant).
_PRUNE = shutil.ignore_patterns(
    "__pycache__",
    "*.pyc",
    "*.pyo",
    "node_modules",
    "dist",
    ".pytest_cache",
    ".vitest",
    "*.log",
)
# Package trees the demo genuinely needs at build/runtime.
_TREES = ("dmcp", "benchmark_advisor", "dmcp-studio")


def _stage(dst: Path) -> None:
    """Assemble the exact tree the Space should contain, at ``dst``."""
    for tree in _TREES:
        shutil.copytree(ROOT / tree, dst / tree, ignore=_PRUNE)
    shutil.copy2(ROOT / "pyproject.toml", dst / "pyproject.toml")
    shutil.copy2(DOCKERFILE, dst / "Dockerfile")  # HF needs it at the Space root
    shutil.copy2(DOCKERIGNORE, dst / ".dockerignore")
    shutil.copy2(SPACE_README, dst / "README.md")  # carries the HF metadata block


def _tree_summary(root: Path) -> tuple[int, int]:
    files = [p for p in root.rglob("*") if p.is_file()]
    return len(files), sum(p.stat().st_size for p in files)


def _load_token(explicit: str | None, token_env: str | None) -> str | None:
    if explicit:
        return explicit
    try:
        from dotenv import load_dotenv

        load_dotenv(ROOT / ".env")
    except Exception:
        pass
    names = [token_env] if token_env else ["HF_TOKEN", "HF_PERSONAL_TOKEN"]
    for name in names:
        if name and os.environ.get(name):
            return os.environ[name]
    return None


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo-id", required=True, help="<user-or-org>/<space>, e.g. TokenWasteGroup/studio")
    ap.add_argument("--private", action="store_true", help="create a private Space (default: public)")
    ap.add_argument("--dry-run", action="store_true", help="stage + list files; do not touch HF")
    ap.add_argument("--wait", action="store_true", help="poll the Space runtime until it is RUNNING")
    ap.add_argument("--token", default=None, help="HF write token literal (avoid; prefer --token-env)")
    ap.add_argument(
        "--token-env",
        default=None,
        help="env var holding the token (default: try HF_TOKEN then HF_PERSONAL_TOKEN from .env)",
    )
    args = ap.parse_args()

    with tempfile.TemporaryDirectory(prefix="dmcp-space-") as tmp:
        staging = Path(tmp) / "space"
        _stage(staging)
        n_files, n_bytes = _tree_summary(staging)
        print(f"staged {n_files} files ({n_bytes / 1e6:.1f} MB) for {args.repo_id}")
        for top in sorted(p.name for p in staging.iterdir()):
            print(f"  - {top}")

        if args.dry_run:
            print("dry-run: nothing uploaded")
            return 0

        token = _load_token(args.token, args.token_env)
        if not token:
            print(
                "error: no HF token (set HF_TOKEN/HF_PERSONAL_TOKEN in .env or --token-env)", file=sys.stderr
            )
            return 2

        from huggingface_hub import HfApi

        api = HfApi(token=token)
        api.create_repo(
            args.repo_id, repo_type="space", space_sdk="docker", private=args.private, exist_ok=True
        )
        api.upload_folder(
            repo_id=args.repo_id,
            repo_type="space",
            folder_path=str(staging),
            commit_message="Deploy DMCP Studio REPLAY demo",
        )
        url = f"https://huggingface.co/spaces/{args.repo_id}"
        print(f"uploaded -> {url}")

        if args.wait:
            print("waiting for the Space to build...")
            deadline = time.time() + 900
            last = ""
            while time.time() < deadline:
                stage = api.get_space_runtime(args.repo_id).stage
                if stage != last:
                    print(f"  stage: {stage}")
                    last = stage
                if stage == "RUNNING":
                    print(f"live: {url}")
                    return 0
                if stage in {"BUILD_ERROR", "RUNTIME_ERROR", "CONFIG_ERROR"}:
                    print(f"error: Space stage {stage} — check the build logs at {url}", file=sys.stderr)
                    return 1
                time.sleep(10)
            print("timed out waiting for RUNNING; check the Space page", file=sys.stderr)
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
